export { default as Navbar } from "./Navbar"
// export { default as Register } from "./Register"
export { default as SignIn } from "./SignIn"
export { default as SignOut } from "./SignOut"
export { default as Home } from "./Home"
export { default as Routines } from "./Routines"
export { default as MyRoutines } from "./MyRoutines"